/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DangKyRouteImport } from './routes/dang-ky'
import { Route as DangNhapRouteImport } from './routes/dang-nhap'
import { Route as QuenMatKhauRouteImport } from './routes/quen-mat-khau'
import { Route as TimPhongRouteImport } from './routes/tim-phong'
import { Route as TrangChuRouteImport } from './routes/trang-chu'
import { Route as PhongIdRouteImport } from './routes/phong.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DangKyRoute = DangKyRouteImport.update({
  id: '/dang-ky',
  path: '/dang-ky',
  getParentRoute: () => rootRouteImport,
} as any)
const DangNhapRoute = DangNhapRouteImport.update({
  id: '/dang-nhap',
  path: '/dang-nhap',
  getParentRoute: () => rootRouteImport,
} as any)
const QuenMatKhauRoute = QuenMatKhauRouteImport.update({
  id: '/quen-mat-khau',
  path: '/quen-mat-khau',
  getParentRoute: () => rootRouteImport,
} as any)
const TimPhongRoute = TimPhongRouteImport.update({
  id: '/tim-phong',
  path: '/tim-phong',
  getParentRoute: () => rootRouteImport,
} as any)
const TrangChuRoute = TrangChuRouteImport.update({
  id: '/trang-chu',
  path: '/trang-chu',
  getParentRoute: () => rootRouteImport,
} as any)
const PhongIdRoute = PhongIdRouteImport.update({
  id: '/phong/$id',
  path: '/phong/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dang-ky': typeof DangKyRoute
  '/dang-nhap': typeof DangNhapRoute
  '/quen-mat-khau': typeof QuenMatKhauRoute
  '/tim-phong': typeof TimPhongRoute
  '/trang-chu': typeof TrangChuRoute
  '/phong/$id': typeof PhongIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dang-ky': typeof DangKyRoute
  '/dang-nhap': typeof DangNhapRoute
  '/quen-mat-khau': typeof QuenMatKhauRoute
  '/tim-phong': typeof TimPhongRoute
  '/trang-chu': typeof TrangChuRoute
  '/phong/$id': typeof PhongIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dang-ky': typeof DangKyRoute
  '/dang-nhap': typeof DangNhapRoute
  '/quen-mat-khau': typeof QuenMatKhauRoute
  '/tim-phong': typeof TimPhongRoute
  '/trang-chu': typeof TrangChuRoute
  '/phong/$id': typeof PhongIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dang-ky'
    | '/dang-nhap'
    | '/quen-mat-khau'
    | '/tim-phong'
    | '/trang-chu'
    | '/phong/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dang-ky'
    | '/dang-nhap'
    | '/quen-mat-khau'
    | '/tim-phong'
    | '/trang-chu'
    | '/phong/$id'
  id:
    | '__root__'
    | '/'
    | '/dang-ky'
    | '/dang-nhap'
    | '/quen-mat-khau'
    | '/tim-phong'
    | '/trang-chu'
    | '/phong/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DangKyRoute: typeof DangKyRoute
  DangNhapRoute: typeof DangNhapRoute
  QuenMatKhauRoute: typeof QuenMatKhauRoute
  TimPhongRoute: typeof TimPhongRoute
  TrangChuRoute: typeof TrangChuRoute
  PhongIdRoute: typeof PhongIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dang-ky': {
      id: '/dang-ky'
      path: '/dang-ky'
      fullPath: '/dang-ky'
      preLoaderRoute: typeof DangKyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dang-nhap': {
      id: '/dang-nhap'
      path: '/dang-nhap'
      fullPath: '/dang-nhap'
      preLoaderRoute: typeof DangNhapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quen-mat-khau': {
      id: '/quen-mat-khau'
      path: '/quen-mat-khau'
      fullPath: '/quen-mat-khau'
      preLoaderRoute: typeof QuenMatKhauRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tim-phong': {
      id: '/tim-phong'
      path: '/tim-phong'
      fullPath: '/tim-phong'
      preLoaderRoute: typeof TimPhongRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trang-chu': {
      id: '/trang-chu'
      path: '/trang-chu'
      fullPath: '/trang-chu'
      preLoaderRoute: typeof TrangChuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phong/$id': {
      id: '/phong/$id'
      path: '/phong/$id'
      fullPath: '/phong/$id'
      preLoaderRoute: typeof PhongIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DangKyRoute: DangKyRoute,
  DangNhapRoute: DangNhapRoute,
  QuenMatKhauRoute: QuenMatKhauRoute,
  TimPhongRoute: TimPhongRoute,
  TrangChuRoute: TrangChuRoute,
  PhongIdRoute: PhongIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
